# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1phob3vTX_SQaiGnNhjG1ye5-tmQiGDm7
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import (precision_score, recall_score, f1_score,
                             confusion_matrix, classification_report,
                             accuracy_score)

tf.random.set_seed(42)
np.random.seed(42)

df = pd.read_csv("WineQT.csv")

print("Dataset shape:", df.shape)
print("\nColumns:", list(df.columns))
print("\nMissing values per column:")
print(df.isnull().sum())
print("\nOriginal quality score distribution:")
print(df["quality"].value_counts().sort_index())

df = df.drop(columns=["Id"])


def bin_quality(q):
    if q <= 5:
        return "Low"
    elif q == 6:
        return "Medium"
    else:
        return "High"


df["quality_class"] = df["quality"].apply(bin_quality)

print("\nBinned class distribution:")
print(df["quality_class"].value_counts())
print("\nClass proportions:")
print(df["quality_class"].value_counts(normalize=True).round(4))

X = df.drop(columns=["quality", "quality_class"]).values
y_labels = df["quality_class"].values

label_encoder = LabelEncoder()
y_encoded_int = label_encoder.fit_transform(y_labels)
class_names = label_encoder.classes_
num_classes = len(class_names)

print("\nEncoded class mapping:")
for i, name in enumerate(class_names):
    print(f"  {i} -> {name}")

y_onehot = tf.keras.utils.to_categorical(y_encoded_int, num_classes=num_classes)

X_train, X_test, y_train, y_test, y_train_int, y_test_int = train_test_split(
    X, y_onehot, y_encoded_int,
    test_size=0.2, random_state=42, stratify=y_encoded_int
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print(f"\nTraining samples: {X_train.shape[0]}")
print(f"Test samples: {X_test.shape[0]}")
print(f"Input features: {X_train.shape[1]}")
print(f"Number of classes: {num_classes}")


def build_model(activation, optimizer, input_dim, num_classes):
    model = tf.keras.Sequential([
        tf.keras.layers.Input(shape=(input_dim,)),
        tf.keras.layers.Dense(64, activation=activation),
        tf.keras.layers.Dense(32, activation=activation),
        tf.keras.layers.Dense(num_classes, activation="softmax")
    ])
    model.compile(optimizer=optimizer,
                  loss="categorical_crossentropy",
                  metrics=["accuracy"])
    return model


def run_experiment(name, activation, optimizer_name):
    tf.random.set_seed(42)

    optimizers = {
        "adam": tf.keras.optimizers.Adam(learning_rate=0.001),
        "sgd": tf.keras.optimizers.SGD(learning_rate=0.01),
        "rmsprop": tf.keras.optimizers.RMSprop(learning_rate=0.001),
    }

    model = build_model(activation, optimizers[optimizer_name],
                        X_train.shape[1], num_classes)

    history = model.fit(
        X_train, y_train,
        validation_split=0.2,
        epochs=100,
        batch_size=32,
        verbose=0
    )

    y_pred_probs = model.predict(X_test, verbose=0)
    y_pred_int = np.argmax(y_pred_probs, axis=1)

    test_acc = accuracy_score(y_test_int, y_pred_int)
    precision = precision_score(y_test_int, y_pred_int,
                                average="weighted", zero_division=0)
    recall = recall_score(y_test_int, y_pred_int,
                          average="weighted", zero_division=0)
    f1 = f1_score(y_test_int, y_pred_int,
                  average="weighted", zero_division=0)

    return {
        "name": name,
        "activation": activation,
        "optimizer": optimizer_name,
        "history": history,
        "train_acc": history.history["accuracy"][-1],
        "val_acc": history.history["val_accuracy"][-1],
        "train_loss": history.history["loss"][-1],
        "val_loss": history.history["val_loss"][-1],
        "test_acc": test_acc,
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "y_pred_int": y_pred_int,
    }


experiments = [
    ("Model 1", "relu", "adam"),
    ("Model 2", "sigmoid", "adam"),
    ("Model 3", "tanh", "adam"),
    ("Model 4", "relu", "sgd"),
    ("Model 5", "relu", "rmsprop"),
]

results = []
for name, activation, optimizer_name in experiments:
    print(f"\nTraining {name}: activation={activation}, optimizer={optimizer_name}")
    result = run_experiment(name, activation, optimizer_name)
    results.append(result)
    print(f"  Test accuracy: {round(result['test_acc'] * 100, 2)}%")

table = pd.DataFrame([{
    "Experiment": r["name"],
    "Activation": r["activation"],
    "Optimizer": r["optimizer"],
    "Train Acc": round(r["train_acc"], 4),
    "Val Acc": round(r["val_acc"], 4),
    "Train Loss": round(r["train_loss"], 4),
    "Val Loss": round(r["val_loss"], 4),
    "Test Acc": round(r["test_acc"], 4),
    "Precision": round(r["precision"], 4),
    "Recall": round(r["recall"], 4),
    "F1": round(r["f1"], 4),
} for r in results])

print("\n" + "=" * 100)
print("COMPARISON TABLE (Precision/Recall/F1 are weighted averages)")
print("=" * 100)
print(table.to_string(index=False))

activation_results = results[:3]
optimizer_results = [results[0], results[3], results[4]]

fig, axes = plt.subplots(2, 2, figsize=(14, 10))

for r in activation_results:
    axes[0, 0].plot(r["history"].history["accuracy"], label=r["activation"])
    axes[0, 1].plot(r["history"].history["val_accuracy"], label=r["activation"])
    axes[1, 0].plot(r["history"].history["loss"], label=r["activation"])
    axes[1, 1].plot(r["history"].history["val_loss"], label=r["activation"])

axes[0, 0].set_title("Training Accuracy vs Epoch (Activation)")
axes[0, 1].set_title("Validation Accuracy vs Epoch (Activation)")
axes[1, 0].set_title("Training Loss vs Epoch (Activation)")
axes[1, 1].set_title("Validation Loss vs Epoch (Activation)")

for ax in axes.flat:
    ax.set_xlabel("Epoch")
    ax.legend()

plt.tight_layout()
plt.savefig("curves_activation.png", dpi=100)
plt.close()

fig, axes = plt.subplots(2, 2, figsize=(14, 10))

for r in optimizer_results:
    axes[0, 0].plot(r["history"].history["accuracy"], label=r["optimizer"])
    axes[0, 1].plot(r["history"].history["val_accuracy"], label=r["optimizer"])
    axes[1, 0].plot(r["history"].history["loss"], label=r["optimizer"])
    axes[1, 1].plot(r["history"].history["val_loss"], label=r["optimizer"])

axes[0, 0].set_title("Training Accuracy vs Epoch (Optimizer)")
axes[0, 1].set_title("Validation Accuracy vs Epoch (Optimizer)")
axes[1, 0].set_title("Training Loss vs Epoch (Optimizer)")
axes[1, 1].set_title("Validation Loss vs Epoch (Optimizer)")

for ax in axes.flat:
    ax.set_xlabel("Epoch")
    ax.legend()

plt.tight_layout()
plt.savefig("curves_optimizer.png", dpi=100)
plt.close()

best_model = max(results, key=lambda r: r["f1"])

print("\n" + "=" * 100)
print(f"BEST MODEL: {best_model['name']} "
      f"(activation={best_model['activation']}, optimizer={best_model['optimizer']})")
print("=" * 100)

cm = confusion_matrix(y_test_int, best_model["y_pred_int"])

print("\nConfusion Matrix (rows=actual, columns=predicted):")
cm_df = pd.DataFrame(cm, index=class_names, columns=class_names)
print(cm_df.to_string())

print("\nPer-class classification report:")
print(classification_report(y_test_int, best_model["y_pred_int"],
                            target_names=class_names, zero_division=0))

plt.figure(figsize=(7, 6))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=class_names, yticklabels=class_names)
plt.title(f"Confusion Matrix: {best_model['name']} "
          f"({best_model['activation']} + {best_model['optimizer']})")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.tight_layout()
plt.savefig("confusion_matrix.png", dpi=100)
plt.close()

per_class_recall = cm.diagonal() / cm.sum(axis=1)
best_class_idx = np.argmax(per_class_recall)
worst_class_idx = np.argmin(per_class_recall)

print(f"\nBest predicted class: {class_names[best_class_idx]} "
      f"(recall={round(per_class_recall[best_class_idx], 4)})")
print(f"Most misclassified class: {class_names[worst_class_idx]} "
      f"(recall={round(per_class_recall[worst_class_idx], 4)})")

cm_offdiag = cm.copy()
np.fill_diagonal(cm_offdiag, 0)
confused_pair = np.unravel_index(np.argmax(cm_offdiag), cm_offdiag.shape)
print(f"Most confused pair: actual '{class_names[confused_pair[0]]}' "
      f"predicted as '{class_names[confused_pair[1]]}' "
      f"({cm_offdiag[confused_pair]} times)")